import React, { Suspense, useState, useEffect, useRef } from 'react';
import { ActivityIndicator, Button } from 'react-native';
import { Canvas} from '@react-three/fiber'
import { OrbitControls, View } from '@react-three/drei'
import { useGLTF } from "@react-three/drei";
import {StyleSheet} from 'react-native';

import CoordinateDisplay from '../components/CoordinateDisplay';

const debugScreen = false;

export default function Robot3dRover() {
  const camera = useRef();
  const [cameraPosition, setCameraPosition] = useState({ x: 0, y: 0, z: 0 });

  const handleButtonClick = () => {
    console.log(camera);
    if (camera.current) {
      camera.current.update();
      const { x, y, z } = camera.current.object.position;
      setCameraPosition({ x, y, z });
    }
  };

  return (
    <Suspense fallback={<ActivityIndicator size="large" color="#8532a8" style={styles.centered}/>}>
      {debugScreen && <Button title="Update Coordinates" onPress={handleButtonClick} />}  
      {debugScreen && <CoordinateDisplay {...cameraPosition} />}
      <Canvas camera={{ position: [7.17, 2.83, -6.47] }} >
        <ambientLight intensity={0.5} />
        <pointLight position={[-10, 10, -10]} />
        <Diff scale={5} position={[0, 0, 0]} />
        <OrbitControls ref={camera}/>
      </Canvas>
    </Suspense>
  );
}

const styles = StyleSheet.create({
  centered: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%"
  }, 
})

function Diff(props) {
  const { nodes, materials } = useGLTF(require('../assets/3d/diff3.glb'));
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_1.geometry}
          material={materials.Shape}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_2.geometry}
          material={materials["Shape.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_3.geometry}
          material={materials["Shape.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_4.geometry}
          material={materials["Shape.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_5.geometry}
          material={materials["Shape.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_6.geometry}
          material={materials["Shape.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_7.geometry}
          material={materials["Shape.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_8.geometry}
          material={materials["Shape.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_9.geometry}
          material={materials["Shape.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_10.geometry}
          material={materials["Shape.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_11.geometry}
          material={materials["Shape.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_12.geometry}
          material={materials["Shape.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_13.geometry}
          material={materials["Shape.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_14.geometry}
          material={materials["Shape.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_15.geometry}
          material={materials["Shape.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_16.geometry}
          material={materials["Shape.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_17.geometry}
          material={materials["Shape.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_18.geometry}
          material={materials["Shape.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_19.geometry}
          material={materials["Shape.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_20.geometry}
          material={materials["Shape.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_21.geometry}
          material={materials["Shape.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_22.geometry}
          material={materials["Shape.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_23.geometry}
          material={materials["Shape.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_24.geometry}
          material={materials["Shape.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_25.geometry}
          material={materials["Shape.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_26.geometry}
          material={materials["Shape.025"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_27.geometry}
          material={materials["Shape.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_28.geometry}
          material={materials["Shape.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_29.geometry}
          material={materials["Shape.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_30.geometry}
          material={materials["Shape.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_31.geometry}
          material={materials["Shape.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_32.geometry}
          material={materials["Shape.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_33.geometry}
          material={materials["Shape.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_34.geometry}
          material={materials["Shape.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_35.geometry}
          material={materials["Shape.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_36.geometry}
          material={materials["Shape.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_37.geometry}
          material={materials["Shape.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_38.geometry}
          material={materials["Shape.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_39.geometry}
          material={materials["Shape.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_40.geometry}
          material={materials["Shape.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_41.geometry}
          material={materials["Shape.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_42.geometry}
          material={materials["Shape.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_43.geometry}
          material={materials["Shape.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_44.geometry}
          material={materials["Shape.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_45.geometry}
          material={materials["Shape.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_46.geometry}
          material={materials["Shape.045"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_47.geometry}
          material={materials["Shape.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_48.geometry}
          material={materials["Shape.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_49.geometry}
          material={materials["Shape.048"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_50.geometry}
          material={materials["Shape.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_51.geometry}
          material={materials["Shape.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_52.geometry}
          material={materials["Shape.051"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_53.geometry}
          material={materials["Shape.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_54.geometry}
          material={materials["Shape.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_55.geometry}
          material={materials["Shape.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_56.geometry}
          material={materials["Shape.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_57.geometry}
          material={materials["Shape.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_58.geometry}
          material={materials["Shape.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_59.geometry}
          material={materials["Shape.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_60.geometry}
          material={materials["Shape.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_61.geometry}
          material={materials["Shape.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_62.geometry}
          material={materials["Shape.061"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_63.geometry}
          material={materials["Shape.062"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_64.geometry}
          material={materials["Shape.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_65.geometry}
          material={materials["Shape.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_66.geometry}
          material={materials["Shape.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_67.geometry}
          material={materials["Shape.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_68.geometry}
          material={materials["Shape.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_69.geometry}
          material={materials["Shape.068"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_70.geometry}
          material={materials["Shape.069"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_71.geometry}
          material={materials["Shape.070"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_72.geometry}
          material={materials["Shape.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_73.geometry}
          material={materials["Shape.072"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_74.geometry}
          material={materials["Shape.073"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_75.geometry}
          material={materials["Shape.074"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_76.geometry}
          material={materials["Shape.075"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_77.geometry}
          material={materials["Shape.076"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_78.geometry}
          material={materials["Shape.077"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_79.geometry}
          material={materials["Shape.078"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_80.geometry}
          material={materials["Shape.079"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_81.geometry}
          material={materials["Shape.080"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_82.geometry}
          material={materials["Shape.081"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_83.geometry}
          material={materials["Shape.082"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_84.geometry}
          material={materials["Shape.083"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_85.geometry}
          material={materials["Shape.084"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_86.geometry}
          material={materials["Shape.085"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_87.geometry}
          material={materials["Shape.086"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_88.geometry}
          material={materials["Shape.087"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_89.geometry}
          material={materials["Shape.088"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_90.geometry}
          material={materials["Shape.089"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_91.geometry}
          material={materials["Shape.090"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_92.geometry}
          material={materials["Shape.091"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_93.geometry}
          material={materials["Shape.092"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_94.geometry}
          material={materials["Shape.093"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_95.geometry}
          material={materials["Shape.094"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_96.geometry}
          material={materials["Shape.095"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_97.geometry}
          material={materials["Shape.096"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_98.geometry}
          material={materials["Shape.097"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_99.geometry}
          material={materials["Shape.098"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_100.geometry}
          material={materials["Shape.099"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_101.geometry}
          material={materials["Shape.100"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_102.geometry}
          material={materials["Shape.101"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_103.geometry}
          material={materials["Shape.102"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_104.geometry}
          material={materials["Shape.103"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_105.geometry}
          material={materials["Shape.104"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_106.geometry}
          material={materials["Shape.105"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_107.geometry}
          material={materials["Shape.106"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_108.geometry}
          material={materials["Shape.107"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_109.geometry}
          material={materials["Shape.108"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_110.geometry}
          material={materials["Shape.109"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_111.geometry}
          material={materials["Shape.110"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_112.geometry}
          material={materials["Shape.111"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_113.geometry}
          material={materials["Shape.112"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_114.geometry}
          material={materials["Shape.113"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_115.geometry}
          material={materials["Shape.114"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_116.geometry}
          material={materials["Shape.115"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_117.geometry}
          material={materials["Shape.116"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_118.geometry}
          material={materials["Shape.117"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_119.geometry}
          material={materials["Shape.118"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_120.geometry}
          material={materials["Shape.119"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_121.geometry}
          material={materials["Shape.120"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_122.geometry}
          material={materials["Shape.121"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_123.geometry}
          material={materials["Shape.122"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_124.geometry}
          material={materials["Shape.123"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_125.geometry}
          material={materials["Shape.124"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_126.geometry}
          material={materials["Shape.125"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_127.geometry}
          material={materials["Shape.126"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_128.geometry}
          material={materials["Shape.127"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_129.geometry}
          material={materials["Shape.128"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_130.geometry}
          material={materials["Shape.129"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_131.geometry}
          material={materials["Shape.130"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_132.geometry}
          material={materials["Shape.131"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_133.geometry}
          material={materials["Shape.132"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_134.geometry}
          material={materials["Shape.133"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_135.geometry}
          material={materials["Shape.134"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_136.geometry}
          material={materials["Shape.135"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_137.geometry}
          material={materials["Shape.136"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_138.geometry}
          material={materials["Shape.137"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_139.geometry}
          material={materials["Shape.138"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_140.geometry}
          material={materials["Shape.139"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_141.geometry}
          material={materials["Shape.140"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_142.geometry}
          material={materials["Shape.141"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_143.geometry}
          material={materials["Shape.142"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_144.geometry}
          material={materials["Shape.143"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_145.geometry}
          material={materials["Shape.144"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_146.geometry}
          material={materials["Shape.145"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_147.geometry}
          material={materials["Shape.146"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_148.geometry}
          material={materials["Shape.147"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_149.geometry}
          material={materials["Shape.148"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_150.geometry}
          material={materials["Shape.149"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_151.geometry}
          material={materials["Shape.150"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_152.geometry}
          material={materials["Shape.151"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_153.geometry}
          material={materials["Shape.152"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_154.geometry}
          material={materials["Shape.153"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_155.geometry}
          material={materials["Shape.154"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_156.geometry}
          material={materials["Shape.155"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_157.geometry}
          material={materials["Shape.156"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_158.geometry}
          material={materials["Shape.157"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_159.geometry}
          material={materials["Shape.158"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_160.geometry}
          material={materials["Shape.159"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_161.geometry}
          material={materials["Shape.160"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_162.geometry}
          material={materials["Shape.161"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_163.geometry}
          material={materials["Shape.162"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_164.geometry}
          material={materials["Shape.163"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_165.geometry}
          material={materials["Shape.164"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_166.geometry}
          material={materials["Shape.165"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_167.geometry}
          material={materials["Shape.166"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_168.geometry}
          material={materials["Shape.167"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_169.geometry}
          material={materials["Shape.168"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_170.geometry}
          material={materials["Shape.169"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_171.geometry}
          material={materials["Shape.170"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_172.geometry}
          material={materials["Shape.171"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_173.geometry}
          material={materials["Shape.172"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_174.geometry}
          material={materials["Shape.173"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_IndexedFaceSet_175.geometry}
          material={materials["Shape.174"]}
        />
      </group>
    </group>
  );
}
useGLTF.preload(require('../assets/3d/diff3.glb'));